import { useEffect, useState } from "react";

function WeatherCard(weatherData) {
  const [date, setDate] = useState("");
  const [day, setDay] = useState("");
  const weatherData1 = {
    location: {
      name: "Toms River",
      region: "New Jersey",
      country: "United States of America",
      lat: 39.95,
      lon: -74.2,
      tz_id: "America/New_York",
      localtime_epoch: 1678075886,
      localtime: "2023-03-05 23:11",
    },
    current: {
      last_updated_epoch: 1678075200,
      last_updated: "2023-03-05 23:00",
      temp_c: 7.8,
      temp_f: 46,
      is_day: 0,
      condition: {
        text: "Clear",
        icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
        code: 1000,
      },
      wind_mph: 9.4,
      wind_kph: 15.1,
      wind_degree: 330,
      wind_dir: "NNW",
      pressure_mb: 1023,
      pressure_in: 30.22,
      precip_mm: 0,
      precip_in: 0,
      humidity: 47,
      cloud: 0,
      feelslike_c: 4.9,
      feelslike_f: 40.8,
      vis_km: 16,
      vis_miles: 9,
      uv: 1,
      gust_mph: 15,
      gust_kph: 24.1,
    },
    forecast: {
      forecastday: [
        {
          date: "2023-03-05",
          date_epoch: 1677974400,
          day: {
            maxtemp_c: 15.3,
            maxtemp_f: 59.5,
            mintemp_c: 1.2,
            mintemp_f: 34.2,
            avgtemp_c: 7.4,
            avgtemp_f: 45.3,
            maxwind_mph: 14.8,
            maxwind_kph: 23.8,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 66,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 3,
          },
          astro: {
            sunrise: "06:24 AM",
            sunset: "05:53 PM",
            moonrise: "04:07 PM",
            moonset: "05:54 AM",
            moon_phase: "Waxing Gibbous",
            moon_illumination: "94",
            is_moon_up: 1,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1677992400,
              time: "2023-03-05 00:00",
              temp_c: 4.1,
              temp_f: 39.4,
              is_day: 0,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
                code: 1006,
              },
              wind_mph: 11.2,
              wind_kph: 18,
              wind_degree: 316,
              wind_dir: "NW",
              pressure_mb: 1015,
              pressure_in: 29.98,
              precip_mm: 0,
              precip_in: 0,
              humidity: 77,
              cloud: 77,
              feelslike_c: 0.2,
              feelslike_f: 32.4,
              windchill_c: 0.2,
              windchill_f: 32.4,
              heatindex_c: 4.1,
              heatindex_f: 39.4,
              dewpoint_c: 0.4,
              dewpoint_f: 32.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 16.1,
              gust_kph: 25.9,
              uv: 1,
            },
            {
              time_epoch: 1677996000,
              time: "2023-03-05 01:00",
              temp_c: 3.4,
              temp_f: 38.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 10.3,
              wind_kph: 16.6,
              wind_degree: 326,
              wind_dir: "NNW",
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              humidity: 81,
              cloud: 22,
              feelslike_c: -0.4,
              feelslike_f: 31.3,
              windchill_c: -0.4,
              windchill_f: 31.3,
              heatindex_c: 3.4,
              heatindex_f: 38.1,
              dewpoint_c: 0.4,
              dewpoint_f: 32.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.5,
              gust_kph: 23.4,
              uv: 1,
            },
            {
              time_epoch: 1677999600,
              time: "2023-03-05 02:00",
              temp_c: 2.8,
              temp_f: 37,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 10.5,
              wind_kph: 16.9,
              wind_degree: 326,
              wind_dir: "NNW",
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 0,
              precip_in: 0,
              humidity: 84,
              cloud: 9,
              feelslike_c: -0.7,
              feelslike_f: 30.7,
              windchill_c: -0.7,
              windchill_f: 30.7,
              heatindex_c: 2.8,
              heatindex_f: 37,
              dewpoint_c: 0.4,
              dewpoint_f: 32.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.8,
              gust_kph: 23.8,
              uv: 1,
            },
            {
              time_epoch: 1678003200,
              time: "2023-03-05 03:00",
              temp_c: 2.4,
              temp_f: 36.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 9.2,
              wind_kph: 14.8,
              wind_degree: 327,
              wind_dir: "NNW",
              pressure_mb: 1018,
              pressure_in: 30.05,
              precip_mm: 0,
              precip_in: 0,
              humidity: 86,
              cloud: 20,
              feelslike_c: -1,
              feelslike_f: 30.2,
              windchill_c: -1,
              windchill_f: 30.2,
              heatindex_c: 2.4,
              heatindex_f: 36.3,
              dewpoint_c: 0.3,
              dewpoint_f: 32.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13,
              gust_kph: 20.9,
              uv: 1,
            },
            {
              time_epoch: 1678006800,
              time: "2023-03-05 04:00",
              temp_c: 1.9,
              temp_f: 35.4,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 8.1,
              wind_kph: 13,
              wind_degree: 319,
              wind_dir: "NW",
              pressure_mb: 1018,
              pressure_in: 30.07,
              precip_mm: 0,
              precip_in: 0,
              humidity: 87,
              cloud: 44,
              feelslike_c: -1.6,
              feelslike_f: 29.1,
              windchill_c: -1.6,
              windchill_f: 29.1,
              heatindex_c: 1.9,
              heatindex_f: 35.4,
              dewpoint_c: -0.1,
              dewpoint_f: 31.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.9,
              gust_kph: 19.1,
              uv: 1,
            },
            {
              time_epoch: 1678010400,
              time: "2023-03-05 05:00",
              temp_c: 1.8,
              temp_f: 35.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 311,
              wind_dir: "NW",
              pressure_mb: 1019,
              pressure_in: 30.08,
              precip_mm: 0,
              precip_in: 0,
              humidity: 81,
              cloud: 0,
              feelslike_c: -1.2,
              feelslike_f: 29.8,
              windchill_c: -1.2,
              windchill_f: 29.8,
              heatindex_c: 1.8,
              heatindex_f: 35.2,
              dewpoint_c: -1.1,
              dewpoint_f: 30,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.5,
              gust_kph: 16.9,
              uv: 1,
            },
            {
              time_epoch: 1678014000,
              time: "2023-03-05 06:00",
              temp_c: 1.4,
              temp_f: 34.5,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.6,
              wind_kph: 9,
              wind_degree: 311,
              wind_dir: "NW",
              pressure_mb: 1019,
              pressure_in: 30.09,
              precip_mm: 0,
              precip_in: 0,
              humidity: 82,
              cloud: 0,
              feelslike_c: -1.9,
              feelslike_f: 28.6,
              windchill_c: -1.9,
              windchill_f: 28.6,
              heatindex_c: 1.4,
              heatindex_f: 34.5,
              dewpoint_c: -1.4,
              dewpoint_f: 29.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.4,
              gust_kph: 15.1,
              uv: 1,
            },
            {
              time_epoch: 1678017600,
              time: "2023-03-05 07:00",
              temp_c: 1.2,
              temp_f: 34.2,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 293,
              wind_dir: "WNW",
              pressure_mb: 1020,
              pressure_in: 30.13,
              precip_mm: 0,
              precip_in: 0,
              humidity: 82,
              cloud: 0,
              feelslike_c: -2.1,
              feelslike_f: 28.2,
              windchill_c: -2.1,
              windchill_f: 28.2,
              heatindex_c: 1.2,
              heatindex_f: 34.2,
              dewpoint_c: -1.5,
              dewpoint_f: 29.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.3,
              gust_kph: 13.3,
              uv: 2,
            },
            {
              time_epoch: 1678021200,
              time: "2023-03-05 08:00",
              temp_c: 1.3,
              temp_f: 34.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 5.8,
              wind_kph: 9.4,
              wind_degree: 284,
              wind_dir: "WNW",
              pressure_mb: 1020,
              pressure_in: 30.13,
              precip_mm: 0,
              precip_in: 0,
              humidity: 82,
              cloud: 1,
              feelslike_c: -2,
              feelslike_f: 28.4,
              windchill_c: -2,
              windchill_f: 28.4,
              heatindex_c: 1.3,
              heatindex_f: 34.3,
              dewpoint_c: -1.5,
              dewpoint_f: 29.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 2,
            },
            {
              time_epoch: 1678024800,
              time: "2023-03-05 09:00",
              temp_c: 3.5,
              temp_f: 38.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 281,
              wind_dir: "WNW",
              pressure_mb: 1021,
              pressure_in: 30.14,
              precip_mm: 0,
              precip_in: 0,
              humidity: 72,
              cloud: 0,
              feelslike_c: 0.5,
              feelslike_f: 32.9,
              windchill_c: 0.5,
              windchill_f: 32.9,
              heatindex_c: 3.5,
              heatindex_f: 38.3,
              dewpoint_c: -1,
              dewpoint_f: 30.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.6,
              gust_kph: 15.5,
              uv: 2,
            },
            {
              time_epoch: 1678028400,
              time: "2023-03-05 10:00",
              temp_c: 5.7,
              temp_f: 42.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.5,
              wind_kph: 13.7,
              wind_degree: 283,
              wind_dir: "WNW",
              pressure_mb: 1021,
              pressure_in: 30.14,
              precip_mm: 0,
              precip_in: 0,
              humidity: 66,
              cloud: 0,
              feelslike_c: 2.8,
              feelslike_f: 37,
              windchill_c: 2.8,
              windchill_f: 37,
              heatindex_c: 5.7,
              heatindex_f: 42.3,
              dewpoint_c: -0.2,
              dewpoint_f: 31.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.5,
              gust_kph: 16.9,
              uv: 3,
            },
            {
              time_epoch: 1678032000,
              time: "2023-03-05 11:00",
              temp_c: 7.5,
              temp_f: 45.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 286,
              wind_dir: "WNW",
              pressure_mb: 1021,
              pressure_in: 30.15,
              precip_mm: 0,
              precip_in: 0,
              humidity: 59,
              cloud: 0,
              feelslike_c: 5,
              feelslike_f: 41,
              windchill_c: 5,
              windchill_f: 41,
              heatindex_c: 7.5,
              heatindex_f: 45.5,
              dewpoint_c: 0.1,
              dewpoint_f: 32.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.7,
              gust_kph: 17.3,
              uv: 3,
            },
            {
              time_epoch: 1678035600,
              time: "2023-03-05 12:00",
              temp_c: 9.2,
              temp_f: 48.6,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 9.6,
              wind_kph: 15.5,
              wind_degree: 286,
              wind_dir: "WNW",
              pressure_mb: 1020,
              pressure_in: 30.13,
              precip_mm: 0,
              precip_in: 0,
              humidity: 55,
              cloud: 40,
              feelslike_c: 6.9,
              feelslike_f: 44.4,
              windchill_c: 6.9,
              windchill_f: 44.4,
              heatindex_c: 9.2,
              heatindex_f: 48.6,
              dewpoint_c: 0.6,
              dewpoint_f: 33.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.2,
              gust_kph: 18,
              uv: 3,
            },
            {
              time_epoch: 1678039200,
              time: "2023-03-05 13:00",
              temp_c: 13,
              temp_f: 55.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 11.9,
              wind_kph: 19.1,
              wind_degree: 289,
              wind_dir: "WNW",
              pressure_mb: 1020,
              pressure_in: 30.12,
              precip_mm: 0,
              precip_in: 0,
              humidity: 52,
              cloud: 0,
              feelslike_c: 11.5,
              feelslike_f: 52.7,
              windchill_c: 11.5,
              windchill_f: 52.7,
              heatindex_c: 13,
              heatindex_f: 55.4,
              dewpoint_c: 3.3,
              dewpoint_f: 37.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.6,
              gust_kph: 22,
              uv: 4,
            },
            {
              time_epoch: 1678042800,
              time: "2023-03-05 14:00",
              temp_c: 14.2,
              temp_f: 57.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 13,
              wind_kph: 20.9,
              wind_degree: 293,
              wind_dir: "WNW",
              pressure_mb: 1020,
              pressure_in: 30.11,
              precip_mm: 0,
              precip_in: 0,
              humidity: 50,
              cloud: 0,
              feelslike_c: 12.9,
              feelslike_f: 55.2,
              windchill_c: 12.9,
              windchill_f: 55.2,
              heatindex_c: 14.2,
              heatindex_f: 57.6,
              dewpoint_c: 3.9,
              dewpoint_f: 39,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15,
              gust_kph: 24.1,
              uv: 4,
            },
            {
              time_epoch: 1678046400,
              time: "2023-03-05 15:00",
              temp_c: 15,
              temp_f: 59,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 13,
              wind_kph: 20.9,
              wind_degree: 298,
              wind_dir: "WNW",
              pressure_mb: 1019,
              pressure_in: 30.1,
              precip_mm: 0,
              precip_in: 0,
              humidity: 50,
              cloud: 0,
              feelslike_c: 13.8,
              feelslike_f: 56.8,
              windchill_c: 13.8,
              windchill_f: 56.8,
              heatindex_c: 15,
              heatindex_f: 59,
              dewpoint_c: 4.6,
              dewpoint_f: 40.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15,
              gust_kph: 24.1,
              uv: 5,
            },
            {
              time_epoch: 1678050000,
              time: "2023-03-05 16:00",
              temp_c: 15.3,
              temp_f: 59.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 14.8,
              wind_kph: 23.8,
              wind_degree: 311,
              wind_dir: "NW",
              pressure_mb: 1019,
              pressure_in: 30.1,
              precip_mm: 0,
              precip_in: 0,
              humidity: 50,
              cloud: 0,
              feelslike_c: 15.3,
              feelslike_f: 59.5,
              windchill_c: 15.3,
              windchill_f: 59.5,
              heatindex_c: 15.3,
              heatindex_f: 59.5,
              dewpoint_c: 4.8,
              dewpoint_f: 40.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 17,
              gust_kph: 27.4,
              uv: 5,
            },
            {
              time_epoch: 1678053600,
              time: "2023-03-05 17:00",
              temp_c: 13.5,
              temp_f: 56.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 14.3,
              wind_kph: 23,
              wind_degree: 320,
              wind_dir: "NW",
              pressure_mb: 1019,
              pressure_in: 30.1,
              precip_mm: 0,
              precip_in: 0,
              humidity: 49,
              cloud: 16,
              feelslike_c: 11.7,
              feelslike_f: 53.1,
              windchill_c: 11.7,
              windchill_f: 53.1,
              heatindex_c: 13.5,
              heatindex_f: 56.3,
              dewpoint_c: 3.1,
              dewpoint_f: 37.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 16.6,
              gust_kph: 26.6,
              uv: 4,
            },
            {
              time_epoch: 1678057200,
              time: "2023-03-05 18:00",
              temp_c: 12.9,
              temp_f: 55.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 13.6,
              wind_kph: 22,
              wind_degree: 323,
              wind_dir: "NW",
              pressure_mb: 1020,
              pressure_in: 30.11,
              precip_mm: 0,
              precip_in: 0,
              humidity: 52,
              cloud: 16,
              feelslike_c: 11.2,
              feelslike_f: 52.2,
              windchill_c: 11.2,
              windchill_f: 52.2,
              heatindex_c: 12.9,
              heatindex_f: 55.2,
              dewpoint_c: 3.2,
              dewpoint_f: 37.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.7,
              gust_kph: 25.2,
              uv: 1,
            },
            {
              time_epoch: 1678060800,
              time: "2023-03-05 19:00",
              temp_c: 11.9,
              temp_f: 53.4,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 10.5,
              wind_kph: 16.9,
              wind_degree: 318,
              wind_dir: "NW",
              pressure_mb: 1021,
              pressure_in: 30.14,
              precip_mm: 0,
              precip_in: 0,
              humidity: 54,
              cloud: 20,
              feelslike_c: 10.2,
              feelslike_f: 50.4,
              windchill_c: 10.2,
              windchill_f: 50.4,
              heatindex_c: 11.9,
              heatindex_f: 53.4,
              dewpoint_c: 3,
              dewpoint_f: 37.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.1,
              gust_kph: 19.4,
              uv: 1,
            },
            {
              time_epoch: 1678064400,
              time: "2023-03-05 20:00",
              temp_c: 10,
              temp_f: 50,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 10.1,
              wind_kph: 16.2,
              wind_degree: 317,
              wind_dir: "NW",
              pressure_mb: 1021,
              pressure_in: 30.16,
              precip_mm: 0,
              precip_in: 0,
              humidity: 57,
              cloud: 30,
              feelslike_c: 7.9,
              feelslike_f: 46.2,
              windchill_c: 7.9,
              windchill_f: 46.2,
              heatindex_c: 10,
              heatindex_f: 50,
              dewpoint_c: 1.9,
              dewpoint_f: 35.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.7,
              gust_kph: 25.2,
              uv: 1,
            },
            {
              time_epoch: 1678068000,
              time: "2023-03-05 21:00",
              temp_c: 9.2,
              temp_f: 48.6,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 9.6,
              wind_kph: 15.5,
              wind_degree: 323,
              wind_dir: "NW",
              pressure_mb: 1022,
              pressure_in: 30.17,
              precip_mm: 0,
              precip_in: 0,
              humidity: 60,
              cloud: 2,
              feelslike_c: 6.8,
              feelslike_f: 44.2,
              windchill_c: 6.8,
              windchill_f: 44.2,
              heatindex_c: 9.2,
              heatindex_f: 48.6,
              dewpoint_c: 1.9,
              dewpoint_f: 35.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.8,
              gust_kph: 23.8,
              uv: 1,
            },
            {
              time_epoch: 1678071600,
              time: "2023-03-05 22:00",
              temp_c: 8.4,
              temp_f: 47.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 10.1,
              wind_kph: 16.2,
              wind_degree: 325,
              wind_dir: "NW",
              pressure_mb: 1022,
              pressure_in: 30.19,
              precip_mm: 0,
              precip_in: 0,
              humidity: 62,
              cloud: 0,
              feelslike_c: 5.9,
              feelslike_f: 42.6,
              windchill_c: 5.9,
              windchill_f: 42.6,
              heatindex_c: 8.4,
              heatindex_f: 47.1,
              dewpoint_c: 1.6,
              dewpoint_f: 34.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.5,
              gust_kph: 23.4,
              uv: 1,
            },
            {
              time_epoch: 1678075200,
              time: "2023-03-05 23:00",
              temp_c: 7.7,
              temp_f: 45.9,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 10.7,
              wind_kph: 17.3,
              wind_degree: 319,
              wind_dir: "NW",
              pressure_mb: 1023,
              pressure_in: 30.2,
              precip_mm: 0,
              precip_in: 0,
              humidity: 62,
              cloud: 0,
              feelslike_c: 5,
              feelslike_f: 41,
              windchill_c: 5,
              windchill_f: 41,
              heatindex_c: 7.7,
              heatindex_f: 45.9,
              dewpoint_c: 1,
              dewpoint_f: 33.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15,
              gust_kph: 24.1,
              uv: 1,
            },
          ],
        },
        {
          date: "2023-03-06",
          date_epoch: 1678060800,
          day: {
            maxtemp_c: 11.9,
            maxtemp_f: 53.4,
            mintemp_c: 1.1,
            mintemp_f: 34,
            avgtemp_c: 6.7,
            avgtemp_f: 44.1,
            maxwind_mph: 11.2,
            maxwind_kph: 18,
            totalprecip_mm: 0.1,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 9.7,
            avgvis_miles: 6,
            avghumidity: 60,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 3,
          },
          astro: {
            sunrise: "06:23 AM",
            sunset: "05:54 PM",
            moonrise: "05:09 PM",
            moonset: "06:19 AM",
            moon_phase: "Waxing Gibbous",
            moon_illumination: "98",
            is_moon_up: 1,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1678078800,
              time: "2023-03-06 00:00",
              temp_c: 6.6,
              temp_f: 43.9,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 9.6,
              wind_kph: 15.5,
              wind_degree: 310,
              wind_dir: "NW",
              pressure_mb: 1023,
              pressure_in: 30.2,
              precip_mm: 0,
              precip_in: 0,
              humidity: 64,
              cloud: 0,
              feelslike_c: 3.4,
              feelslike_f: 38.1,
              windchill_c: 3.4,
              windchill_f: 38.1,
              heatindex_c: 6.6,
              heatindex_f: 43.9,
              dewpoint_c: 0.3,
              dewpoint_f: 32.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.3,
              gust_kph: 23,
              uv: 1,
            },
            {
              time_epoch: 1678082400,
              time: "2023-03-06 01:00",
              temp_c: 5.7,
              temp_f: 42.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 9.2,
              wind_kph: 14.8,
              wind_degree: 302,
              wind_dir: "WNW",
              pressure_mb: 1023,
              pressure_in: 30.2,
              precip_mm: 0,
              precip_in: 0,
              humidity: 67,
              cloud: 0,
              feelslike_c: 2.2,
              feelslike_f: 36,
              windchill_c: 2.2,
              windchill_f: 36,
              heatindex_c: 5.7,
              heatindex_f: 42.3,
              dewpoint_c: 0.1,
              dewpoint_f: 32.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.9,
              gust_kph: 22.3,
              uv: 1,
            },
            {
              time_epoch: 1678086000,
              time: "2023-03-06 02:00",
              temp_c: 4.8,
              temp_f: 40.6,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 9.8,
              wind_kph: 15.8,
              wind_degree: 310,
              wind_dir: "NW",
              pressure_mb: 1023,
              pressure_in: 30.21,
              precip_mm: 0,
              precip_in: 0,
              humidity: 69,
              cloud: 0,
              feelslike_c: 1,
              feelslike_f: 33.8,
              windchill_c: 1,
              windchill_f: 33.8,
              heatindex_c: 4.8,
              heatindex_f: 40.6,
              dewpoint_c: -0.3,
              dewpoint_f: 31.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15,
              gust_kph: 24.1,
              uv: 1,
            },
            {
              time_epoch: 1678089600,
              time: "2023-03-06 03:00",
              temp_c: 4,
              temp_f: 39.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 10.7,
              wind_kph: 17.3,
              wind_degree: 318,
              wind_dir: "NW",
              pressure_mb: 1024,
              pressure_in: 30.22,
              precip_mm: 0,
              precip_in: 0,
              humidity: 72,
              cloud: 0,
              feelslike_c: 0,
              feelslike_f: 32,
              windchill_c: 0,
              windchill_f: 32,
              heatindex_c: 4,
              heatindex_f: 39.2,
              dewpoint_c: -0.6,
              dewpoint_f: 30.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.7,
              gust_kph: 25.2,
              uv: 1,
            },
            {
              time_epoch: 1678093200,
              time: "2023-03-06 04:00",
              temp_c: 3.1,
              temp_f: 37.6,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 11.2,
              wind_kph: 18,
              wind_degree: 320,
              wind_dir: "NW",
              pressure_mb: 1024,
              pressure_in: 30.23,
              precip_mm: 0,
              precip_in: 0,
              humidity: 74,
              cloud: 0,
              feelslike_c: -1.2,
              feelslike_f: 29.8,
              windchill_c: -1.2,
              windchill_f: 29.8,
              heatindex_c: 3.1,
              heatindex_f: 37.6,
              dewpoint_c: -1,
              dewpoint_f: 30.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 16.1,
              gust_kph: 25.9,
              uv: 1,
            },
            {
              time_epoch: 1678096800,
              time: "2023-03-06 05:00",
              temp_c: 2.4,
              temp_f: 36.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 9.8,
              wind_kph: 15.8,
              wind_degree: 312,
              wind_dir: "NW",
              pressure_mb: 1024,
              pressure_in: 30.23,
              precip_mm: 0,
              precip_in: 0,
              humidity: 76,
              cloud: 0,
              feelslike_c: -2,
              feelslike_f: 28.4,
              windchill_c: -2,
              windchill_f: 28.4,
              heatindex_c: 2.4,
              heatindex_f: 36.3,
              dewpoint_c: -1.4,
              dewpoint_f: 29.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.5,
              gust_kph: 23.4,
              uv: 1,
            },
            {
              time_epoch: 1678100400,
              time: "2023-03-06 06:00",
              temp_c: 1.8,
              temp_f: 35.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 306,
              wind_dir: "NW",
              pressure_mb: 1024,
              pressure_in: 30.23,
              precip_mm: 0,
              precip_in: 0,
              humidity: 77,
              cloud: 0,
              feelslike_c: -2.6,
              feelslike_f: 27.3,
              windchill_c: -2.6,
              windchill_f: 27.3,
              heatindex_c: 1.8,
              heatindex_f: 35.2,
              dewpoint_c: -1.7,
              dewpoint_f: 28.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.1,
              gust_kph: 22.7,
              uv: 1,
            },
            {
              time_epoch: 1678104000,
              time: "2023-03-06 07:00",
              temp_c: 1.2,
              temp_f: 34.2,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 9.2,
              wind_kph: 14.8,
              wind_degree: 300,
              wind_dir: "WNW",
              pressure_mb: 1024,
              pressure_in: 30.24,
              precip_mm: 0,
              precip_in: 0,
              humidity: 79,
              cloud: 0,
              feelslike_c: -3.4,
              feelslike_f: 25.9,
              windchill_c: -3.4,
              windchill_f: 25.9,
              heatindex_c: 1.2,
              heatindex_f: 34.2,
              dewpoint_c: -2.1,
              dewpoint_f: 28.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.3,
              gust_kph: 23,
              uv: 2,
            },
            {
              time_epoch: 1678107600,
              time: "2023-03-06 08:00",
              temp_c: 1.1,
              temp_f: 34,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.7,
              wind_kph: 14,
              wind_degree: 304,
              wind_dir: "NW",
              pressure_mb: 1024,
              pressure_in: 30.24,
              precip_mm: 0,
              precip_in: 0,
              humidity: 79,
              cloud: 0,
              feelslike_c: -3.5,
              feelslike_f: 25.7,
              windchill_c: -3.5,
              windchill_f: 25.7,
              heatindex_c: 1.1,
              heatindex_f: 34,
              dewpoint_c: -2.2,
              dewpoint_f: 28,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.2,
              gust_kph: 21.2,
              uv: 2,
            },
            {
              time_epoch: 1678111200,
              time: "2023-03-06 09:00",
              temp_c: 2.6,
              temp_f: 36.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 9.6,
              wind_kph: 15.5,
              wind_degree: 313,
              wind_dir: "NW",
              pressure_mb: 1024,
              pressure_in: 30.23,
              precip_mm: 0,
              precip_in: 0,
              humidity: 71,
              cloud: 0,
              feelslike_c: -1.7,
              feelslike_f: 28.9,
              windchill_c: -1.7,
              windchill_f: 28.9,
              heatindex_c: 2.6,
              heatindex_f: 36.7,
              dewpoint_c: -2.2,
              dewpoint_f: 28,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.3,
              gust_kph: 19.8,
              uv: 2,
            },
            {
              time_epoch: 1678114800,
              time: "2023-03-06 10:00",
              temp_c: 4.1,
              temp_f: 39.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 319,
              wind_dir: "NW",
              pressure_mb: 1024,
              pressure_in: 30.22,
              precip_mm: 0,
              precip_in: 0,
              humidity: 63,
              cloud: 0,
              feelslike_c: 0,
              feelslike_f: 32,
              windchill_c: 0,
              windchill_f: 32,
              heatindex_c: 4.1,
              heatindex_f: 39.4,
              dewpoint_c: -2.4,
              dewpoint_f: 27.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11,
              gust_kph: 17.6,
              uv: 2,
            },
            {
              time_epoch: 1678118400,
              time: "2023-03-06 11:00",
              temp_c: 8.7,
              temp_f: 47.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.7,
              wind_kph: 14,
              wind_degree: 311,
              wind_dir: "NW",
              pressure_mb: 1023,
              pressure_in: 30.21,
              precip_mm: 0,
              precip_in: 0,
              humidity: 56,
              cloud: 0,
              feelslike_c: 6,
              feelslike_f: 42.8,
              windchill_c: 6,
              windchill_f: 42.8,
              heatindex_c: 8.7,
              heatindex_f: 47.7,
              dewpoint_c: 0.3,
              dewpoint_f: 32.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.1,
              gust_kph: 16.2,
              uv: 3,
            },
            {
              time_epoch: 1678122000,
              time: "2023-03-06 12:00",
              temp_c: 10.3,
              temp_f: 50.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.5,
              wind_kph: 13.7,
              wind_degree: 308,
              wind_dir: "NW",
              pressure_mb: 1022,
              pressure_in: 30.19,
              precip_mm: 0,
              precip_in: 0,
              humidity: 50,
              cloud: 0,
              feelslike_c: 8.1,
              feelslike_f: 46.6,
              windchill_c: 8.1,
              windchill_f: 46.6,
              heatindex_c: 10.3,
              heatindex_f: 50.5,
              dewpoint_c: 0.4,
              dewpoint_f: 32.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 4,
            },
            {
              time_epoch: 1678125600,
              time: "2023-03-06 13:00",
              temp_c: 9.1,
              temp_f: 48.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.1,
              wind_kph: 13,
              wind_degree: 303,
              wind_dir: "WNW",
              pressure_mb: 1021,
              pressure_in: 30.16,
              precip_mm: 0,
              precip_in: 0,
              humidity: 46,
              cloud: 0,
              feelslike_c: 6.9,
              feelslike_f: 44.4,
              windchill_c: 6.9,
              windchill_f: 44.4,
              heatindex_c: 9.1,
              heatindex_f: 48.4,
              dewpoint_c: -1.8,
              dewpoint_f: 28.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.2,
              gust_kph: 14.8,
              uv: 3,
            },
            {
              time_epoch: 1678129200,
              time: "2023-03-06 14:00",
              temp_c: 10.9,
              temp_f: 51.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 7.2,
              wind_kph: 11.5,
              wind_degree: 303,
              wind_dir: "WNW",
              pressure_mb: 1020,
              pressure_in: 30.13,
              precip_mm: 0,
              precip_in: 0,
              humidity: 43,
              cloud: 0,
              feelslike_c: 9.4,
              feelslike_f: 48.9,
              windchill_c: 9.4,
              windchill_f: 48.9,
              heatindex_c: 10.9,
              heatindex_f: 51.6,
              dewpoint_c: -1.1,
              dewpoint_f: 30,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.3,
              gust_kph: 13.3,
              uv: 4,
            },
            {
              time_epoch: 1678132800,
              time: "2023-03-06 15:00",
              temp_c: 11.1,
              temp_f: 52,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.5,
              wind_kph: 13.7,
              wind_degree: 297,
              wind_dir: "WNW",
              pressure_mb: 1019,
              pressure_in: 30.1,
              precip_mm: 0,
              precip_in: 0,
              humidity: 42,
              cloud: 9,
              feelslike_c: 9.9,
              feelslike_f: 49.8,
              windchill_c: 9.9,
              windchill_f: 49.8,
              heatindex_c: 11.1,
              heatindex_f: 52,
              dewpoint_c: -1.3,
              dewpoint_f: 29.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 4,
            },
            {
              time_epoch: 1678136400,
              time: "2023-03-06 16:00",
              temp_c: 10,
              temp_f: 50,
              is_day: 1,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
                code: 1006,
              },
              wind_mph: 7.8,
              wind_kph: 12.6,
              wind_degree: 294,
              wind_dir: "WNW",
              pressure_mb: 1018,
              pressure_in: 30.07,
              precip_mm: 0,
              precip_in: 0,
              humidity: 45,
              cloud: 65,
              feelslike_c: 8.7,
              feelslike_f: 47.7,
              windchill_c: 8.7,
              windchill_f: 47.7,
              heatindex_c: 10,
              heatindex_f: 50,
              dewpoint_c: -1.4,
              dewpoint_f: 29.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.6,
              gust_kph: 15.5,
              uv: 3,
            },
            {
              time_epoch: 1678140000,
              time: "2023-03-06 17:00",
              temp_c: 11.9,
              temp_f: 53.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 298,
              wind_dir: "WNW",
              pressure_mb: 1018,
              pressure_in: 30.06,
              precip_mm: 0,
              precip_in: 0,
              humidity: 43,
              cloud: 0,
              feelslike_c: 10.7,
              feelslike_f: 51.3,
              windchill_c: 10.7,
              windchill_f: 51.3,
              heatindex_c: 11.9,
              heatindex_f: 53.4,
              dewpoint_c: -0.2,
              dewpoint_f: 31.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.1,
              gust_kph: 16.2,
              uv: 4,
            },
            {
              time_epoch: 1678143600,
              time: "2023-03-06 18:00",
              temp_c: 11.9,
              temp_f: 53.4,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6,
              wind_kph: 9.7,
              wind_degree: 305,
              wind_dir: "NW",
              pressure_mb: 1018,
              pressure_in: 30.05,
              precip_mm: 0,
              precip_in: 0,
              humidity: 45,
              cloud: 0,
              feelslike_c: 10.9,
              feelslike_f: 51.6,
              windchill_c: 10.9,
              windchill_f: 51.6,
              heatindex_c: 11.9,
              heatindex_f: 53.4,
              dewpoint_c: 0.4,
              dewpoint_f: 32.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.3,
              gust_kph: 13.3,
              uv: 1,
            },
            {
              time_epoch: 1678147200,
              time: "2023-03-06 19:00",
              temp_c: 9.8,
              temp_f: 49.6,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 4.5,
              wind_kph: 7.2,
              wind_degree: 320,
              wind_dir: "NW",
              pressure_mb: 1018,
              pressure_in: 30.05,
              precip_mm: 0,
              precip_in: 0,
              humidity: 46,
              cloud: 27,
              feelslike_c: 8.8,
              feelslike_f: 47.8,
              windchill_c: 8.8,
              windchill_f: 47.8,
              heatindex_c: 9.8,
              heatindex_f: 49.6,
              dewpoint_c: -1.3,
              dewpoint_f: 29.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.2,
              gust_kph: 11.5,
              uv: 1,
            },
            {
              time_epoch: 1678150800,
              time: "2023-03-06 20:00",
              temp_c: 8.9,
              temp_f: 48,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 332,
              wind_dir: "NNW",
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 0,
              precip_in: 0,
              humidity: 49,
              cloud: 20,
              feelslike_c: 7.8,
              feelslike_f: 46,
              windchill_c: 7.8,
              windchill_f: 46,
              heatindex_c: 8.9,
              heatindex_f: 48,
              dewpoint_c: -1.3,
              dewpoint_f: 29.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.3,
              gust_kph: 10.1,
              uv: 1,
            },
            {
              time_epoch: 1678154400,
              time: "2023-03-06 21:00",
              temp_c: 7.8,
              temp_f: 46,
              is_day: 0,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 5.6,
              wind_kph: 9,
              wind_degree: 351,
              wind_dir: "N",
              pressure_mb: 1014,
              pressure_in: 29.96,
              precip_mm: 0.1,
              precip_in: 0,
              humidity: 56,
              cloud: 82,
              feelslike_c: 6.2,
              feelslike_f: 43.2,
              windchill_c: 6.2,
              windchill_f: 43.2,
              heatindex_c: 7.8,
              heatindex_f: 46,
              dewpoint_c: -0.5,
              dewpoint_f: 31.1,
              will_it_rain: 1,
              chance_of_rain: 82,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.1,
              gust_kph: 13,
              uv: 1,
            },
            {
              time_epoch: 1678158000,
              time: "2023-03-06 22:00",
              temp_c: 6.6,
              temp_f: 43.9,
              is_day: 0,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 8.1,
              wind_kph: 13,
              wind_degree: 357,
              wind_dir: "N",
              pressure_mb: 1015,
              pressure_in: 29.96,
              precip_mm: 0,
              precip_in: 0,
              humidity: 65,
              cloud: 96,
              feelslike_c: 4,
              feelslike_f: 39.2,
              windchill_c: 4,
              windchill_f: 39.2,
              heatindex_c: 6.6,
              heatindex_f: 43.9,
              dewpoint_c: 0.4,
              dewpoint_f: 32.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.4,
              gust_kph: 18.4,
              uv: 1,
            },
            {
              time_epoch: 1678161600,
              time: "2023-03-06 23:00",
              temp_c: 7.2,
              temp_f: 45,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 7.8,
              wind_kph: 12.6,
              wind_degree: 23,
              wind_dir: "NNE",
              pressure_mb: 1016,
              pressure_in: 30,
              precip_mm: 0,
              precip_in: 0,
              humidity: 59,
              cloud: 36,
              feelslike_c: 5.7,
              feelslike_f: 42.3,
              windchill_c: 5.7,
              windchill_f: 42.3,
              heatindex_c: 7.2,
              heatindex_f: 45,
              dewpoint_c: -0.3,
              dewpoint_f: 31.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 10.3,
              gust_kph: 16.6,
              uv: 1,
            },
          ],
        },
        {
          date: "2023-03-07",
          date_epoch: 1678147200,
          day: {
            maxtemp_c: 10.9,
            maxtemp_f: 51.6,
            mintemp_c: 0.8,
            mintemp_f: 33.4,
            avgtemp_c: 4.4,
            avgtemp_f: 39.8,
            maxwind_mph: 20.6,
            maxwind_kph: 33.1,
            totalprecip_mm: 1.6,
            totalprecip_in: 0.06,
            totalsnow_cm: 0.6,
            avgvis_km: 8.9,
            avgvis_miles: 5,
            avghumidity: 70,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 75,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            uv: 1,
          },
          astro: {
            sunrise: "06:21 AM",
            sunset: "05:55 PM",
            moonrise: "06:11 PM",
            moonset: "06:42 AM",
            moon_phase: "Full Moon",
            moon_illumination: "100",
            is_moon_up: 1,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1678165200,
              time: "2023-03-07 00:00",
              temp_c: 5,
              temp_f: 41,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 8.5,
              wind_kph: 13.7,
              wind_degree: 39,
              wind_dir: "NE",
              pressure_mb: 1012,
              pressure_in: 29.87,
              precip_mm: 0,
              precip_in: 0,
              humidity: 80,
              cloud: 62,
              feelslike_c: 2,
              feelslike_f: 35.6,
              windchill_c: 2,
              windchill_f: 35.6,
              heatindex_c: 5,
              heatindex_f: 41,
              dewpoint_c: 1.9,
              dewpoint_f: 35.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.4,
              gust_kph: 18.4,
              uv: 1,
            },
            {
              time_epoch: 1678168800,
              time: "2023-03-07 01:00",
              temp_c: 4.6,
              temp_f: 40.3,
              is_day: 0,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 7.2,
              wind_kph: 11.5,
              wind_degree: 47,
              wind_dir: "NE",
              pressure_mb: 1011,
              pressure_in: 29.84,
              precip_mm: 0.1,
              precip_in: 0,
              humidity: 84,
              cloud: 100,
              feelslike_c: 1.9,
              feelslike_f: 35.4,
              windchill_c: 1.9,
              windchill_f: 35.4,
              heatindex_c: 4.6,
              heatindex_f: 40.3,
              dewpoint_c: 2.2,
              dewpoint_f: 36,
              will_it_rain: 0,
              chance_of_rain: 62,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.6,
              gust_kph: 15.5,
              uv: 1,
            },
            {
              time_epoch: 1678172400,
              time: "2023-03-07 02:00",
              temp_c: 6.8,
              temp_f: 44.2,
              is_day: 0,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 6.7,
              wind_kph: 10.8,
              wind_degree: 11,
              wind_dir: "NNE",
              pressure_mb: 1012,
              pressure_in: 29.88,
              precip_mm: 0,
              precip_in: 0,
              humidity: 60,
              cloud: 100,
              feelslike_c: 6.7,
              feelslike_f: 44.1,
              windchill_c: 6.7,
              windchill_f: 44.1,
              heatindex_c: 6.8,
              heatindex_f: 44.2,
              dewpoint_c: -0.4,
              dewpoint_f: 31.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.9,
              gust_kph: 14.4,
              uv: 1,
            },
            {
              time_epoch: 1678176000,
              time: "2023-03-07 03:00",
              temp_c: 4.4,
              temp_f: 39.9,
              is_day: 0,
              condition: {
                text: "Light drizzle",
                icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
                code: 1153,
              },
              wind_mph: 6,
              wind_kph: 9.7,
              wind_degree: 44,
              wind_dir: "NE",
              pressure_mb: 1008,
              pressure_in: 29.78,
              precip_mm: 0.3,
              precip_in: 0.01,
              humidity: 89,
              cloud: 100,
              feelslike_c: 2,
              feelslike_f: 35.6,
              windchill_c: 2,
              windchill_f: 35.6,
              heatindex_c: 4.4,
              heatindex_f: 39.9,
              dewpoint_c: 2.8,
              dewpoint_f: 37,
              will_it_rain: 0,
              chance_of_rain: 63,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 8.1,
              gust_kph: 13,
              uv: 1,
            },
            {
              time_epoch: 1678179600,
              time: "2023-03-07 04:00",
              temp_c: 4.2,
              temp_f: 39.6,
              is_day: 0,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 6.7,
              wind_kph: 10.8,
              wind_degree: 45,
              wind_dir: "NE",
              pressure_mb: 1007,
              pressure_in: 29.74,
              precip_mm: 0,
              precip_in: 0,
              humidity: 90,
              cloud: 100,
              feelslike_c: 1.5,
              feelslike_f: 34.7,
              windchill_c: 1.5,
              windchill_f: 34.7,
              heatindex_c: 4.2,
              heatindex_f: 39.6,
              dewpoint_c: 2.7,
              dewpoint_f: 36.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.2,
              gust_kph: 14.8,
              uv: 1,
            },
            {
              time_epoch: 1678183200,
              time: "2023-03-07 05:00",
              temp_c: 6.3,
              temp_f: 43.3,
              is_day: 0,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 8.1,
              wind_kph: 13,
              wind_degree: 26,
              wind_dir: "NNE",
              pressure_mb: 1007,
              pressure_in: 29.74,
              precip_mm: 0,
              precip_in: 0,
              humidity: 73,
              cloud: 100,
              feelslike_c: 3.7,
              feelslike_f: 38.7,
              windchill_c: 3.7,
              windchill_f: 38.7,
              heatindex_c: 6.3,
              heatindex_f: 43.3,
              dewpoint_c: 1.8,
              dewpoint_f: 35.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9,
              vis_miles: 5,
              gust_mph: 10.7,
              gust_kph: 17.3,
              uv: 1,
            },
            {
              time_epoch: 1678186800,
              time: "2023-03-07 06:00",
              temp_c: 3,
              temp_f: 37.4,
              is_day: 0,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 9.8,
              wind_kph: 15.8,
              wind_degree: 20,
              wind_dir: "NNE",
              pressure_mb: 1006,
              pressure_in: 29.7,
              precip_mm: 0,
              precip_in: 0,
              humidity: 95,
              cloud: 100,
              feelslike_c: -0.8,
              feelslike_f: 30.6,
              windchill_c: -0.8,
              windchill_f: 30.6,
              heatindex_c: 3,
              heatindex_f: 37.4,
              dewpoint_c: 2.2,
              dewpoint_f: 36,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.8,
              gust_kph: 20.5,
              uv: 1,
            },
            {
              time_epoch: 1678190400,
              time: "2023-03-07 07:00",
              temp_c: 2.1,
              temp_f: 35.8,
              is_day: 1,
              condition: {
                text: "Light sleet",
                icon: "//cdn.weatherapi.com/weather/64x64/day/317.png",
                code: 1204,
              },
              wind_mph: 11.4,
              wind_kph: 18.4,
              wind_degree: 1,
              wind_dir: "N",
              pressure_mb: 1007,
              pressure_in: 29.72,
              precip_mm: 0.3,
              precip_in: 0.01,
              humidity: 96,
              cloud: 100,
              feelslike_c: -2.4,
              feelslike_f: 27.7,
              windchill_c: -2.4,
              windchill_f: 27.7,
              heatindex_c: 2.1,
              heatindex_f: 35.8,
              dewpoint_c: 1.6,
              dewpoint_f: 34.9,
              will_it_rain: 1,
              chance_of_rain: 75,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9,
              vis_miles: 5,
              gust_mph: 14.5,
              gust_kph: 23.4,
              uv: 1,
            },
            {
              time_epoch: 1678194000,
              time: "2023-03-07 08:00",
              temp_c: 5.2,
              temp_f: 41.4,
              is_day: 1,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                code: 1009,
              },
              wind_mph: 12.5,
              wind_kph: 20.2,
              wind_degree: 346,
              wind_dir: "NNW",
              pressure_mb: 1005,
              pressure_in: 29.68,
              precip_mm: 0,
              precip_in: 0,
              humidity: 86,
              cloud: 100,
              feelslike_c: 0.9,
              feelslike_f: 33.6,
              windchill_c: 0.9,
              windchill_f: 33.6,
              heatindex_c: 5.2,
              heatindex_f: 41.4,
              dewpoint_c: 3.1,
              dewpoint_f: 37.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.9,
              gust_kph: 25.6,
              uv: 2,
            },
            {
              time_epoch: 1678197600,
              time: "2023-03-07 09:00",
              temp_c: 1.1,
              temp_f: 34,
              is_day: 1,
              condition: {
                text: "Heavy snow",
                icon: "//cdn.weatherapi.com/weather/64x64/day/338.png",
                code: 1225,
              },
              wind_mph: 13,
              wind_kph: 20.9,
              wind_degree: 335,
              wind_dir: "NNW",
              pressure_mb: 1009,
              pressure_in: 29.78,
              precip_mm: 0.5,
              precip_in: 0.02,
              humidity: 94,
              cloud: 100,
              feelslike_c: -4,
              feelslike_f: 24.8,
              windchill_c: -4,
              windchill_f: 24.8,
              heatindex_c: 1.1,
              heatindex_f: 34,
              dewpoint_c: 0.3,
              dewpoint_f: 32.5,
              will_it_rain: 0,
              chance_of_rain: 61,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 16.8,
              gust_kph: 27,
              uv: 1,
            },
            {
              time_epoch: 1678201200,
              time: "2023-03-07 10:00",
              temp_c: 2.4,
              temp_f: 36.3,
              is_day: 1,
              condition: {
                text: "Patchy moderate snow",
                icon: "//cdn.weatherapi.com/weather/64x64/day/329.png",
                code: 1216,
              },
              wind_mph: 13.6,
              wind_kph: 22,
              wind_degree: 337,
              wind_dir: "NNW",
              pressure_mb: 1009,
              pressure_in: 29.79,
              precip_mm: 0.2,
              precip_in: 0.01,
              humidity: 75,
              cloud: 86,
              feelslike_c: -2.5,
              feelslike_f: 27.5,
              windchill_c: -2.5,
              windchill_f: 27.5,
              heatindex_c: 2.4,
              heatindex_f: 36.3,
              dewpoint_c: -1.6,
              dewpoint_f: 29.1,
              will_it_rain: 0,
              chance_of_rain: 68,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 7,
              vis_miles: 4,
              gust_mph: 16.3,
              gust_kph: 26.3,
              uv: 1,
            },
            {
              time_epoch: 1678204800,
              time: "2023-03-07 11:00",
              temp_c: 2.2,
              temp_f: 36,
              is_day: 1,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                code: 1009,
              },
              wind_mph: 15.7,
              wind_kph: 25.2,
              wind_degree: 328,
              wind_dir: "NNW",
              pressure_mb: 1006,
              pressure_in: 29.71,
              precip_mm: 0,
              precip_in: 0,
              humidity: 89,
              cloud: 100,
              feelslike_c: -3.3,
              feelslike_f: 26.1,
              windchill_c: -3.3,
              windchill_f: 26.1,
              heatindex_c: 2.2,
              heatindex_f: 36,
              dewpoint_c: 0.5,
              dewpoint_f: 32.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 5,
              vis_miles: 3,
              gust_mph: 18.1,
              gust_kph: 29.2,
              uv: 1,
            },
            {
              time_epoch: 1678208400,
              time: "2023-03-07 12:00",
              temp_c: 4.8,
              temp_f: 40.6,
              is_day: 1,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 18.1,
              wind_kph: 29.2,
              wind_degree: 327,
              wind_dir: "NNW",
              pressure_mb: 1010,
              pressure_in: 29.81,
              precip_mm: 0.1,
              precip_in: 0,
              humidity: 52,
              cloud: 73,
              feelslike_c: -0.1,
              feelslike_f: 31.8,
              windchill_c: -0.1,
              windchill_f: 31.8,
              heatindex_c: 4.8,
              heatindex_f: 40.6,
              dewpoint_c: -4.1,
              dewpoint_f: 24.6,
              will_it_rain: 0,
              chance_of_rain: 70,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 20.8,
              gust_kph: 33.5,
              uv: 1,
            },
            {
              time_epoch: 1678212000,
              time: "2023-03-07 13:00",
              temp_c: 6.1,
              temp_f: 43,
              is_day: 1,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 19.5,
              wind_kph: 31.3,
              wind_degree: 327,
              wind_dir: "NNW",
              pressure_mb: 1010,
              pressure_in: 29.83,
              precip_mm: 0.1,
              precip_in: 0,
              humidity: 50,
              cloud: 70,
              feelslike_c: 1.4,
              feelslike_f: 34.5,
              windchill_c: 1.4,
              windchill_f: 34.5,
              heatindex_c: 6.1,
              heatindex_f: 43,
              dewpoint_c: -3.6,
              dewpoint_f: 25.5,
              will_it_rain: 1,
              chance_of_rain: 72,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 22.4,
              gust_kph: 36,
              uv: 2,
            },
            {
              time_epoch: 1678215600,
              time: "2023-03-07 14:00",
              temp_c: 5.7,
              temp_f: 42.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 20.1,
              wind_kph: 32.4,
              wind_degree: 324,
              wind_dir: "NW",
              pressure_mb: 1008,
              pressure_in: 29.75,
              precip_mm: 0,
              precip_in: 0,
              humidity: 65,
              cloud: 15,
              feelslike_c: 1.8,
              feelslike_f: 35.2,
              windchill_c: 1.8,
              windchill_f: 35.2,
              heatindex_c: 5.7,
              heatindex_f: 42.3,
              dewpoint_c: -0.4,
              dewpoint_f: 31.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 23,
              gust_kph: 37.1,
              uv: 3,
            },
            {
              time_epoch: 1678219200,
              time: "2023-03-07 15:00",
              temp_c: 7.6,
              temp_f: 45.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 20.6,
              wind_kph: 33.1,
              wind_degree: 323,
              wind_dir: "NW",
              pressure_mb: 1011,
              pressure_in: 29.84,
              precip_mm: 0,
              precip_in: 0,
              humidity: 50,
              cloud: 7,
              feelslike_c: 3.2,
              feelslike_f: 37.8,
              windchill_c: 3.2,
              windchill_f: 37.8,
              heatindex_c: 7.6,
              heatindex_f: 45.7,
              dewpoint_c: -2.2,
              dewpoint_f: 28,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 23.7,
              gust_kph: 38.2,
              uv: 3,
            },
            {
              time_epoch: 1678222800,
              time: "2023-03-07 16:00",
              temp_c: 7.7,
              temp_f: 45.9,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 20.1,
              wind_kph: 32.4,
              wind_degree: 320,
              wind_dir: "NW",
              pressure_mb: 1011,
              pressure_in: 29.86,
              precip_mm: 0,
              precip_in: 0,
              humidity: 51,
              cloud: 5,
              feelslike_c: 3.4,
              feelslike_f: 38.1,
              windchill_c: 3.4,
              windchill_f: 38.1,
              heatindex_c: 7.7,
              heatindex_f: 45.9,
              dewpoint_c: -1.8,
              dewpoint_f: 28.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 23,
              gust_kph: 37.1,
              uv: 3,
            },
            {
              time_epoch: 1678226400,
              time: "2023-03-07 17:00",
              temp_c: 10.9,
              temp_f: 51.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 20.1,
              wind_kph: 32.4,
              wind_degree: 319,
              wind_dir: "NW",
              pressure_mb: 1008,
              pressure_in: 29.75,
              precip_mm: 0,
              precip_in: 0,
              humidity: 49,
              cloud: 0,
              feelslike_c: 8.3,
              feelslike_f: 46.9,
              windchill_c: 8.3,
              windchill_f: 46.9,
              heatindex_c: 10.9,
              heatindex_f: 51.6,
              dewpoint_c: 0.6,
              dewpoint_f: 33.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 23,
              gust_kph: 37.1,
              uv: 4,
            },
            {
              time_epoch: 1678230000,
              time: "2023-03-07 18:00",
              temp_c: 4.4,
              temp_f: 39.9,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 20.4,
              wind_kph: 32.8,
              wind_degree: 323,
              wind_dir: "NW",
              pressure_mb: 1013,
              pressure_in: 29.92,
              precip_mm: 0,
              precip_in: 0,
              humidity: 59,
              cloud: 52,
              feelslike_c: -1,
              feelslike_f: 30.2,
              windchill_c: -1,
              windchill_f: 30.2,
              heatindex_c: 4.4,
              heatindex_f: 39.9,
              dewpoint_c: -2.9,
              dewpoint_f: 26.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 23.5,
              gust_kph: 37.8,
              uv: 1,
            },
            {
              time_epoch: 1678233600,
              time: "2023-03-07 19:00",
              temp_c: 2.9,
              temp_f: 37.2,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 19.9,
              wind_kph: 32,
              wind_degree: 325,
              wind_dir: "NW",
              pressure_mb: 1014,
              pressure_in: 29.95,
              precip_mm: 0,
              precip_in: 0,
              humidity: 62,
              cloud: 61,
              feelslike_c: -2.9,
              feelslike_f: 26.8,
              windchill_c: -2.9,
              windchill_f: 26.8,
              heatindex_c: 2.9,
              heatindex_f: 37.2,
              dewpoint_c: -3.7,
              dewpoint_f: 25.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 22.8,
              gust_kph: 36.7,
              uv: 1,
            },
            {
              time_epoch: 1678237200,
              time: "2023-03-07 20:00",
              temp_c: 4.6,
              temp_f: 40.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 20.1,
              wind_kph: 32.4,
              wind_degree: 324,
              wind_dir: "NW",
              pressure_mb: 1011,
              pressure_in: 29.86,
              precip_mm: 0,
              precip_in: 0,
              humidity: 49,
              cloud: 0,
              feelslike_c: -0.5,
              feelslike_f: 31.1,
              windchill_c: -0.5,
              windchill_f: 31.1,
              heatindex_c: 4.6,
              heatindex_f: 40.3,
              dewpoint_c: -5.2,
              dewpoint_f: 22.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 25.9,
              gust_kph: 41.8,
              uv: 1,
            },
            {
              time_epoch: 1678240800,
              time: "2023-03-07 21:00",
              temp_c: 0.8,
              temp_f: 33.4,
              is_day: 0,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
                code: 1006,
              },
              wind_mph: 19.2,
              wind_kph: 31,
              wind_degree: 323,
              wind_dir: "NW",
              pressure_mb: 1016,
              pressure_in: 29.99,
              precip_mm: 0,
              precip_in: 0,
              humidity: 62,
              cloud: 71,
              feelslike_c: -5.5,
              feelslike_f: 22.1,
              windchill_c: -5.5,
              windchill_f: 22.1,
              heatindex_c: 0.8,
              heatindex_f: 33.4,
              dewpoint_c: -5.6,
              dewpoint_f: 21.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 24.8,
              gust_kph: 40,
              uv: 1,
            },
            {
              time_epoch: 1678244400,
              time: "2023-03-07 22:00",
              temp_c: 0.8,
              temp_f: 33.4,
              is_day: 0,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
                code: 1006,
              },
              wind_mph: 18.6,
              wind_kph: 29.9,
              wind_degree: 326,
              wind_dir: "NNW",
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              humidity: 61,
              cloud: 79,
              feelslike_c: -5.4,
              feelslike_f: 22.3,
              windchill_c: -5.4,
              windchill_f: 22.3,
              heatindex_c: 0.8,
              heatindex_f: 33.4,
              dewpoint_c: -5.9,
              dewpoint_f: 21.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 23.5,
              gust_kph: 37.8,
              uv: 1,
            },
            {
              time_epoch: 1678248000,
              time: "2023-03-07 23:00",
              temp_c: 0.9,
              temp_f: 33.6,
              is_day: 0,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
                code: 1006,
              },
              wind_mph: 18.3,
              wind_kph: 29.5,
              wind_degree: 327,
              wind_dir: "NNW",
              pressure_mb: 1014,
              pressure_in: 29.95,
              precip_mm: 0,
              precip_in: 0,
              humidity: 62,
              cloud: 77,
              feelslike_c: -5.4,
              feelslike_f: 22.3,
              windchill_c: -5.4,
              windchill_f: 22.3,
              heatindex_c: 0.9,
              heatindex_f: 33.6,
              dewpoint_c: -5.5,
              dewpoint_f: 22.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 23.5,
              gust_kph: 37.8,
              uv: 1,
            },
          ],
        },
      ],
    },
  };

  function setDateAndDay(weatherData, i = 0, current = true) {
    const days = [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
    ];
    if (current) {
      let date = new Date(weatherData?.location?.localtime.split(" ")[0]);
      date = new Date(date.setDate(date.getDate()));
      const day = date.getDay();
      setDate(date.toLocaleDateString("en-US", { timeZone: "UTC" }));
      setDay(days[day]);
    } else {
      let date = new Date(weatherData?.date);
      date = new Date(date.setDate(date.getDate()));
      const day = date.getDay();
      return {
        date: date.toLocaleDateString("en-US", { timeZone: "UTC" }),
        day: days[day],
      };
    }
  }

  useEffect(() => {
    setDateAndDay(weatherData1);
  });

  return (
    <div className="flex flex-col my-auto text-white w-1/4 h-3/4 rounded-3xl shadow-lg bg-opacity-90 bg-gradient-to-tr from-green-600 to-green-900">
      <div className="flex">
        <div className="flex flex-col w-full ml-12">
          <img
            className="w-24"
            src={"https://" + weatherData1.current.condition.icon.slice(2)}
            alt=""
          ></img>
          <h2 className="text-3xl font-bold">{`${Math.round(
            weatherData1.forecast.forecastday[0].day.mintemp_f
          )}°/${Math.round(
            weatherData1.forecast.forecastday[0].day.maxtemp_f
          )}°`}</h2>

          <div className="flex w-full justify-between">
            <h1 className="text-6xl font-bold">
              {weatherData1?.current?.condition.text}
            </h1>
            <div className="flex flex-col mr-8">
              <h2>{day}</h2>
              <h2>{date}</h2>
            </div>
          </div>
          <div className="flex align-middle">
            <svg
              className="w-4 h-4 my-auto mr-1"
              fill="#ffffff"
              height="800px"
              width="800px"
              version="1.1"
              id="Capa_1"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 297 297"
            >
              <g>
                <path
                  d="M148.5,0C87.43,0,37.747,49.703,37.747,110.797c0,91.026,99.729,179.905,103.976,183.645
		c1.936,1.705,4.356,2.559,6.777,2.559c2.421,0,4.841-0.853,6.778-2.559c4.245-3.739,103.975-92.618,103.975-183.645
		C259.253,49.703,209.57,0,148.5,0z M148.5,272.689c-22.049-21.366-90.243-93.029-90.243-161.892
		c0-49.784,40.483-90.287,90.243-90.287s90.243,40.503,90.243,90.287C238.743,179.659,170.549,251.322,148.5,272.689z"
                />
                <path
                  d="M148.5,59.183c-28.273,0-51.274,23.154-51.274,51.614c0,28.461,23.001,51.614,51.274,51.614
		c28.273,0,51.274-23.153,51.274-51.614C199.774,82.337,176.773,59.183,148.5,59.183z M148.5,141.901
		c-16.964,0-30.765-13.953-30.765-31.104c0-17.15,13.801-31.104,30.765-31.104c16.964,0,30.765,13.953,30.765,31.104
		C179.265,127.948,165.464,141.901,148.5,141.901z"
                />
              </g>
            </svg>
            <h2 className="">
              {`${weatherData1.location.name}, ${
                weatherData1.location.country === "United States of America"
                  ? weatherData1.location.region
                  : weatherData1.location.country
              }`}
            </h2>
          </div>
        </div>
      </div>
      <div>
        <ul className="mt-2">
          {weatherData1.forecast.forecastday.map((days, i) => {
            if (i === 0) {
              return null;
            }
            const forecastDayInfo = setDateAndDay(days, i, false);
            return (
              <li
                className={
                  i === 2
                    ? "flex justify-between w-80 mx-auto text-xl rounded-3xl border shadow-lg my-auto border-gray-400 border-opacity-70"
                    : "flex justify-between mb-2 w-80 mx-auto text-xl rounded-3xl border shadow-lg my-auto border-gray-400 border-opacity-70"
                }
                key={i}
              >
                <div className="flex ml-8">
                  <img
                    className="h-20 w-20 my-auto"
                    src={"https://" + days?.day?.condition?.icon.slice(2)}
                    alt=""
                  ></img>
                  <div className="flex flex-col my-auto">
                    <h2 className="text-xs">
                      {i === 0 ? "Today" : forecastDayInfo.day}
                    </h2>
                    <h1 className="break-normal">
                      {days.day.condition.text === "Patchy rain possible"
                        ? "Scattered Showers"
                        : days.day.condition.text}
                    </h1>
                  </div>
                </div>

                <h1 className="my-auto mr-2">{`${Math.round(
                  days.day.mintemp_f
                )}°/${Math.round(days.day.maxtemp_f)}°`}</h1>
              </li>
            );
          })}
        </ul>
      </div>
      <div className="my-auto text-xs">
        <div className="flex justify-between">
          <div className="flex flex-col h-12 w-24 border border-gray-400 mt-3 mb-1 mx-auto w-34 px-2 rounded-l-3xl rounded-r-3xl shadow-lg">
            <h2 className="mt-2 mx-auto">
              {Math.round(weatherData1.current.temp_f)}°
            </h2>
            <h2 className="mb-2 mx-auto">Temperature</h2>
          </div>
          <div className="flex flex-col h-12 w-24 border border-gray-400 border-opacity-70 mt-3 mb-1 mx-auto w-34 px-2 rounded-l-3xl rounded-r-3xl shadow-lg">
            <h2 className="mt-2 mx-auto">
              {Math.round(weatherData1.current.feelslike_f)}°
            </h2>
            <h2 className="mb-2 mx-auto">Real Feel</h2>
          </div>
        </div>
        <div className="flex h-16 justify-between text-xs">
          <div className="flex flex-col h-12 w-24 border border-gray-400 border-opacity-70 mt-1 mb-1 mx-auto w-34 px-2 rounded-3xl shadow-lg">
            <h2 className="mt-2 mx-auto">{weatherData1.current.temp_f}%</h2>
            <h2 className="mb-2 mx-auto">Humidity</h2>
          </div>
          <div className="flex flex-col h-12 w-24 border border-gray-400 border-opacity-70 mt-1 mb-1 mx-auto w-34 px-2 rounded-3xl shadow-lg">
            <h2 className="mt-2 mx-auto">
              {Math.round(weatherData1.current.wind_mph)}mph
            </h2>
            <h2 className="mb-2 mx-auto">Wind Speed</h2>
          </div>
        </div>
      </div>
    </div>
  );
  //   return weatherData.current ? (
  //     <div className="text-lg text-black bg-purple-400 border border-black mx-auto w-72 h-80 rounded-2xl flex justify-between">
  //       <div className="flex flex-col justify-between w-1/2 ml-2 my-2">
  //         <div className="text-base">
  //           <h3 className="">{`${weatherData.location.name}, `}</h3>
  //           <h3>
  //             {`${
  //               weatherData.location.country === "United States of America"
  //                 ? weatherData.location.region
  //                 : weatherData.location.country
  //             }
  //             `}
  //           </h3>
  //           <h2 className="text-5xl">{`${Math.round(
  //             weatherData.current.temp_f
  //           )}°`}</h2>
  //         </div>

  //         <div className="m-2">
  //           <img
  //             className="w-24 h-24"
  //             src={"https://" + weatherData.current.condition.icon.slice(2)}
  //             alt="IMG not found"
  //           ></img>
  //           <h3 className="text-lg font-bold h-16">
  //             {weatherData.current.condition.text === "Patchy rain possible"
  //               ? "Scattered Showers"
  //               : weatherData.current.condition.text}
  //           </h3>
  //         </div>
  //       </div>

  //       <div className="flex flex-col justify-between">
  //         <div className="flex flex-col m-2">
  //           <p className="flex justify-end">{date}</p>
  //           <p className="flex justify-end">{day}</p>
  //         </div>
  //         {
  //           <div className="flex justify-end m-2 ml-12">
  //             Feels like {Math.round(weatherData.current.feelslike_f)}°
  //           </div>
  //         }
  //       </div>
  //     </div>
  //   ) : (
  //     <div></div>
  //   );
}

export default WeatherCard;
